---
# TODO: Separate vagrant and ansible settings ?

### Vagrant ###

vagrant_box: bento/ubuntu-16.04
vagrant_user: vagrant

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: ubn.dev
vagrant_machine_name: ubn
# vagrant_ip: 0.0.0.0
vagrant_ip: 192.168.0.66

# A list of synced folders, with the keys 'local_path', 'destination', 'id', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares). See
# http://docs.ubnvm.com/en/latest/extras/syncing-folders/ for more info.
vagrant_synced_folders:
  - local_path: ~/sites/drupal7
    destination: /srv/drupal7
    id: ubn
    type: nfs
    create: true

# Memory and CPU to use for this VM.
vagrant_memory: 2048
vagrant_cpus: 2

### End Vagrant ###

### UBNext ###

# Drupal development VM instance settings
drupal_core_path: "/srv/drupal7/ubnext/web"
drupal_domain: "drupal7.ubn.dev"
# TODO: provision more devel settings and/or modules 
drupal_enable_modules: [ 'devel' ]
drupal_account_name: ubnadmin
drupal_account_pass: ubnadmin
drupal_mysql_user: drupal7_ubnext
drupal_mysql_password: drupal7_ubnext
drupal_mysql_database: drupal7_ubnext
drupal_deploy: false
drupal_deploy_db: false

# Development git-repo settings
drupal_git_repo: "https://github.com/ub-digit/ubnext.git"
drupal_git_checkout_path : "/srv/drupal7/ubnext/"
drupal_git_branch: "master" #TODO: should probably create and switch to dev/devel, not work against master
drupal_git_version: "HEAD"

# Drupal production instance settings
drupal_production_core_path: "/var/drupal/platforms/m-test.current"
drupal_production_domain: "m-test.ub.gu.se"
# (drupal_production_user set from prompt)

# Cron jobs are added to the root user's crontab. Keys include name (required),
# minute, hour, day, weekday, month, job (required), and state.
ubnvm_cron_jobs:
  - {
    name: "UBNext Drupal Cron",
    minute: "*/15",
    job: "drush -r {{ drupal_core_path }} core-cron"
  }

# Drupal VM automatically creates a drush alias file in your ~/.drush folder if
# this variable is 'true'.
configure_local_drush_aliases: true

### End UBNext ###

### NGINX ###

### END NGINX ###

### Apache ###

# Apache VirtualHosts. Add one for each site you are running inside the VM. For
# multisite deployments, you can point multiple servernames at one documentroot.
#
# Could use "{{ drupal_domain }}" for drupal vhost entry, but then will be
# impossible for vagrant-hostupdater to figure out hostname
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"

apache_listen_port: 8080
apache_remove_default_vhost: true
apache_mods_enabled:
  - expires.load
  - rewrite.load
apache_mods_disabled:
  - ssl.load

### End Apache ###

### Extra packages ###

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, make set this value to an empty set, e.g. `[]`.
installed_extras:
  - xdebug
  # - xhprof

### End Extra packages ###

# You can configure almost anything else on the server in the rest of this file.
# extra_security_enabled: false

### Drush ###
drush_version: master
drush_keep_updated: true
drush_composer_cli_options: "--prefer-dist --no-interaction"
### End Drush ###

### Firewall ###
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "443"
# firewall_log_dropped_packets: false
### End Firewall ###

### PHP7 ###
php_memory_limit: "256M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"
### End PHP7 ###

### Composer ###
composer_path: /usr/bin/composer
composer_home_path: '/home/vagrant/.composer'
# composer_global_packages:
#   - { name: phpunit/phpunit, release: '@stable' }
### End Composer ###

### MySQL ###
mysql_root_password: root
mysql_slow_query_log_enabled: false
mysql_slow_query_time: 2
mysql_wait_timeout: 300

# MySQL Databases and users. If build_from_makefile is true, first database will
# be used for the makefile-built site.
mysql_databases:
  - name: "{{ drupal_mysql_database }}"
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: "{{ drupal_mysql_user }}"
    host: "%"
    password: "{{ drupal_mysql_password }}"
    priv: "{{ drupal_mysql_database }}.*:ALL"
### End MySQL ###

### XDebug ###
php_xdebug_default_enable: 0
php_xdebug_coverage_enable: 0
php_xdebug_cli_enable: 0
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: sublime.xdebug
php_xdebug_max_nesting_level: 256
### End XDebub ###
