---
ubnext_stages:
  devel:
    hostname: drupal7.ubn.dev
    drupal_core_path: "/srv/drupal7/ubnext/web"
    drush_alias_options:
      remote-user: vagrant
      ssh-options: -o PasswordAuthentication=no -i ~/.vagrant.d/insecure_private_key
