---

- name: Ensure production server is a known host
  lineinfile:
    dest: /root/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + drupal_production_domain) }}"
    regexp: "^{{ drupal_production_domain }}"

 - name: Test drush
  command: >
    {{ drush_path }} @{{ drupal_production_domain }} status
  #when: drupal_site.stat.exists == false
  sudo: no
  register: develop_drush_status

 - debug: var=develop_drush_status
