---

- name: Ensure production server is a known host
  lineinfile:
    dest: /root/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + drupal_production_domain) }}"
    regexp: "^{{ drupal_production_domain }}"

- name: Test drush (with password)
  expect:
    command: {{ drush_path }} @{{ drupal_production_domain }} status
    responses:
      (?i)password: "{{ drupal_production_password }}"
    #timeout:
  become: no
  register: develop_drush_status

#- name: Test drush
#  command: >
#    {{ drush_path }} @{{ drupal_production_domain }} status
  #  sudo: no
  # register: develop_drush_status

- debug: var=develop_drush_status
