---
- name: Update apt cache if needed.
  apt: update_cache=yes cache_valid_time=86400

- name: Get software for Python-based control.
  apt: "name={{ item }} state=installed"
  with_items:
    - curl
    - python-apt
    - python-pycurl
    - build-essential
    - sudo
    - unzip
    - vim-nox
    - nmap #Perhaps no need for this
    - redis-server #TODO: this is not the place for this, make sure service is started etc

- name: Disable the ufw firewall (since we use a simple iptables firewall).
  service: name=ufw state=stopped
  when: ansible_distribution == "Ubuntu"
