---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "Debian.yml"

- name: Define apache_packages.
  set_fact:
    apache_packages: "{{ __apache_packages | list }}"
  when: apache_packages is not defined

# Setup/install tasks.
- include: setup-Debian.yml
- include_vars: apache-24.yml

# Configure Apache.
- include: configure-Debian.yml

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: yes
