---
- hosts: all

  vars_files:
    - ../default.config.yml

  vars_prompt:
    - name: "drupal_production_user"
      prompt: "Enter production server username"
      private: yes
      # Temporary fix to avoid ssh-forwarding sudo-issue mess
    - name: "drupal_production_password"
      prompt: "Enter production server password"
      private: yes

  pre_tasks:
    - include: tasks/init-debian.yml

  roles:
    # Essential roles.
    - geerlingguy.firewall
    - geerlingguy.git
    - geerlingguy.apache
    - geerlingguy.apache-php-fpm
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-pecl
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush

    # Conditionally-installed roles.
    - { role: geerlingguy.php-xdebug, when: '"xdebug" in installed_extras' }

    # Roles for security and stability on production.
    # - { role: geerlingguy.security, when: extra_security_enabled }

  tasks:
    - name: Check if Drupal is already set up.
      stat: "path={{ drupal_core_path }}/index.php"
      register: drupal_site

    - include: tasks/sshd.yml
    - include: tasks/www.yml
    - include: tasks/apparmor.yml

    # Checkout ubnext code
    # - include: tasks/drupal7-ubn-dev.yml
    #  when: drupal_deploy

    # Configure drush aliases
    - include: tasks/drush-aliases.yml

    # Import database from production
    # - include: tasks/drupal7-ubn-dev-db.yml
    #  when: drupal_deploy and drupal_deploy_db

    # Setup drupal cron
    - include: tasks/cron.yml
